
[functions.elevenlabs-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/elevenlabs-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/elevenlabs-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/elevenlabs-webhook/*.html" ]

[functions.get-elevenlabs-calls]
enabled = true
verify_jwt = false
import_map = "./functions/get-elevenlabs-calls/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-elevenlabs-calls/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-elevenlabs-calls/*.html" ]

[functions.whatsapp-elevenlabs-bot]
enabled = true
verify_jwt = false
import_map = "./functions/whatsapp-elevenlabs-bot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/whatsapp-elevenlabs-bot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/whatsapp-elevenlabs-bot/*.html" ]

[functions.meta-whatsapp-outbound]
enabled = true
verify_jwt = false
import_map = "./functions/meta-whatsapp-outbound/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/meta-whatsapp-outbound/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/meta-whatsapp-outbound/*.html" ]

[functions.delete-crm-lead]
enabled = true
verify_jwt = false
import_map = "./functions/delete-crm-lead/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-crm-lead/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-crm-lead/*.html" ]
